language: python

python:
  - "2.7"

install:

# add repository (from iris .travis.yml)
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3E5C1192
  - yes | sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update

# install dependencies
  - sudo apt-get install python-pip python-scipy cython
  - sudo apt-get install gfortran
  - sudo apt-get install libudunits2-dev libhdf5-serial-dev libnetcdf-dev netcdf-bin
  - sudo apt-get install libgeos-dev libproj-dev
  - sudo apt-get install make unzip python-sphinx
  - sudo /usr/bin/pip install --use-mirrors shapely nose pyshp pep8 mock
#  - sudo /usr/bin/pip install matplotlib
  - sudo /usr/bin/pip install pyke netCDF4
  - sudo /usr/bin/pip install cdat-lite
  - sudo /usr/bin/pip install coverage

#-----------------------------------------------------------------------------
# create a directory to download and install dependencies in
#
  - mkdir ../prereqs
  - cd ../prereqs

#-----------------------------------------------------------------------------
# Dependencies for iris and iris itself
#
# grib api
#  - sudo apt-get install libjasper-dev
#  - sudo apt-get build-dep libgrib-api-1.9.9 libgrib-api-dev libgrib-api-tools
#  - wget https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.9.16.tar.gz --no-check-certificate
#  - tar -xvf grib_api-1.9.16.tar.gz
#  - cd grib_api-1.9.16/
#  - CFLAGS="-fPIC" ./configure --with-jasper=/usr/local/lib --disable-fortran --enable-python
#  - make
#  - sudo make install
#  - cd python
#  - sudo /usr/bin/python setup.py install
#  - cd ../..
# distutils
  - wget http://python-distribute.org/distribute_setup.py
  - sudo /usr/bin/python distribute_setup.py
# cartopy
  - git clone git://github.com/SciTools/cartopy.git
  - cd cartopy
  - git checkout v0.7.0
  - sudo /usr/bin/python setup.py install
  - cd ..
# iris
  - git clone git://github.com/SciTools/iris.git
  - cd iris
  - git checkout v1.3.0
  - /usr/bin/python setup.py std_names
  - sudo /usr/bin/python setup.py install
  - cd ..

#-----------------------------------------------------------------------------
# pyspharm is the primary dependency of windspharm
#
# pyspharm (1.0.8 required)
  - wget http://pyspharm.googlecode.com/files/pyspharm-1.0.8.tar.gz
  - tar xfvz pyspharm-1.0.8.tar.gz
  - cd pyspharm-1.0.8
  - yes | sudo /usr/bin/python setup.py install
  - cd ../../windspharm

script:
  - /usr/bin/python tests.py --verbosity=2 --with-coverage --cover-package=windspharm

notifications:
  email: false
